swagger: "2.0"
info:
  description: "This is a MVP web store for XenElectronics"
  version: "0.0.1"
  title: "XenElectronics Web Store"
  contact:
    email: "rayson.ljk@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/"
schemes:
- "https"
- "http"
paths:
  /search:
    get:
      summary: "Get products for sale"
      description: ""
      operationId: "search"
      parameters:
      - name: "category"
        in: "query"
        description: "category of products to get for"
        required: true
        type: "string"
        enum: ["home_appliances", "smart_watches", "mobile_phones"]
      responses:
        "200":
          description: "A complex object array of products"
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                price:
                  type: number
        "404":
          description: "Category not found"
  /checkout:
    put:
      summary: "Saves cart items to database"
      description: ""
      operationId: "saveCart"
      parameters:
      - name: "products"
        in: "body"
        description: "The order to create"
        required: true
        schema:
          type: "array"
          items:
            type: "object"
            required:
            - "product"
            properties:
              productId:
                type: "integer"
              quantity:
                type: "integer"
      responses:
        "201":
          description: "OK"
          schema:
            type: "object"
            properties:
              orderId:
                type: "integer"
    post:
      summary: "Informs server that payment has been made"
      description: ""
      operationId: "payment"
      parameters:
      - name: "orderId"
        in: "body"
        description: "The order to pay for"
        required: true
        schema:
          type: "integer"
          example:
            orderId: 0
      responses:
        "200":
          description: "OK"
          schema:
            type: "object"
            properties:
              orderId:
                type: "integer"

        