swagger: "2.0"
info:
  description: "This is a MVP web store for XenElectronics"
  version: "0.0.1"
  title: "XenElectronics Web Store"
  contact:
    email: "rayson.ljk@gmail.com"
basePath: "/"
schemes:
- "https"
- "http"
paths:
  /search:
    get:
      summary: "Get products for sale"
      description: "Searches for products matching given filters."
      operationId: "search"
      parameters:
      - name: "category"
        in: "query"
        description: "category of products for filter; repeated"
        required: false
        type: "string"
        enum: ["home_appliances", "smart_watches", "mobile_phones"]
      responses:
        "200":
          description: "A complex object array of products"
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                price:
                  type: number
                description:
                  type: string
                categories:
                  type: array
                  items:
                    type: string
        "400":
          description: "Bad inputs for filters e.g. invalid category"
  /checkout:
    put:
      summary: "Saves cart items to database and create a checkout"
      description: "Saves what items this user is purchasing alongside the quantity of each item"
      operationId: "saveCart"
      parameters:
      - name: "products"
        in: "body"
        description: "The checkout to create"
        required: true
        schema:
          type: "array"
          items:
            type: "object"
            required:
            - "product"
            properties:
              productId:
                type: "integer"
              quantity:
                type: "integer"
      responses:
        "201":
          description: "OK"
          schema:
            type: "object"
            properties:
              checkoutId:
                type: "integer"
  /checkout/{checkoutId}:
    post:
      summary: "Informs server that payment has been made"
      description: ""
      operationId: "payment"
      parameters:
      - name: "checkoutId"
        in: "path"
        description: "The order to pay for"
        required: true
        type: "integer"
      responses:
        "200":
          description: "OK"

        