/*
 * XenElectronics Web Store
 * This is a MVP web store for XenElectronics
 *
 * OpenAPI spec version: 0.0.1
 * Contact: rayson.ljk@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.XenElectronicsWebStore);
  }
}(this, function(expect, XenElectronicsWebStore) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new XenElectronicsWebStore.DefaultApi();
  });

  describe('(package)', function() {
    describe('DefaultApi', function() {
      describe('getCheckout', function() {
        it('should call getCheckout successfully', function(done) {
          // TODO: uncomment, update parameter values for getCheckout call and complete the assertions
          /*

          instance.getCheckout(checkoutId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(XenElectronicsWebStore.InlineResponse201);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('login', function() {
        it('should call login successfully', function(done) {
          // TODO: uncomment, update parameter values for login call and complete the assertions
          /*

          instance.login(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(XenElectronicsWebStore.InlineResponse2001);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('payment', function() {
        it('should call payment successfully', function(done) {
          // TODO: uncomment, update parameter values for payment call
          /*

          instance.payment(body, checkoutId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('saveCart', function() {
        it('should call saveCart successfully', function(done) {
          // TODO: uncomment, update parameter values for saveCart call and complete the assertions
          /*

          instance.saveCart(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(XenElectronicsWebStore.InlineResponse201);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('search', function() {
        it('should call search successfully', function(done) {
          // TODO: uncomment, update parameter values for search call and complete the assertions
          /*
          var opts = {};

          instance.search(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(XenElectronicsWebStore.InlineResponse200);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
