/*
 * XenElectronics Web Store
 * This is a MVP web store for XenElectronics
 *
 * OpenAPI spec version: 0.0.1
 * Contact: rayson.ljk@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.XenElectronicsWebStore);
  }
}(this, function(expect, XenElectronicsWebStore) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse201', function() {
      beforeEach(function() {
        instance = new XenElectronicsWebStore.InlineResponse201();
      });

      it('should create an instance of InlineResponse201', function() {
        // TODO: update the code to test InlineResponse201
        expect(instance).to.be.a(XenElectronicsWebStore.InlineResponse201);
      });

      it('should have the property checkoutId (base name: "checkoutId")', function() {
        // TODO: update the code to test the property checkoutId
        expect(instance).to.have.property('checkoutId');
        // expect(instance.checkoutId).to.be(expectedValueLiteral);
      });

    });
  });

}));
